name: Test personalizado

description: " Este es un test personalizado con inputs and runs "

runs:
  using: "Composite"
  

  steps:
    - name: Saludar
      run: echo "Hola Gomera" 
      shell: bash