name: Prueba Unitaria

on:
  push:
    branches: 
      - master

  pull_request:
    branches:
      - master


jobs:
  Test:
    name: My test
    runs-on: ubuntu-latest

    steps:
      - name: Gomera CI
        run: echo " Hola Darli "

      - name: Mariela CD
        run: echo " Hola Dayelin "


    