name: Prueba Unitaria (Test)

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


jobs:
  Testing_CI:
    name: Integracion Continua
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mylql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3606:3606

    steps:
      - name: clonar repo
        uses: actions/checkout@v4.2.2
        
      - name: Install python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"
      
      - name: Version Python
        run: python --version
  
  Testing_CD:
    name: Despliegue Continue
    needs: Testing_CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Gomera CD
        run: echo " Despliegue continue con Gomera Romero "
      
      - name: Darli CD
        run: echo " Despliegue continue con Darli Diaz "

      - name: clonar repo
        uses: actions/checkout@v4.2.2
      
      - name: ls
        uses: ./.github/actions/my_action
        with:
          testing: " Amo la Programacion como nadie mas lo ha hecho. "
          dev: " Amo EL Lenguaje de Programacion Python "
          
              


    