name: Prueba Unitaria (Test)

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


jobs:
  Testing_CI:
    name: Integracion Continua
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3606:3606

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: clonar repo
        uses: actions/checkout@v4.2.2
        
      - name: Install python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"
      
      - name: Version Python
        run: python --version
  
  Testing_CD:
    name: Despliegue Continue
    needs: Testing_CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Gomera CD
        run: echo " Despliegue continue con Gomera Romero "
      
      - name: Darli CD
        run: echo " Despliegue continue con Darli Diaz "
  
  Test_personalizado:
    name: Testing Personalizado
    needs: Testing_CD
    runs-on: ubuntu-latest
          
    steps:       
      - name: clonar repo
        uses: actions/checkout@v4.2.2

      - name: ls
        uses: ./.github/actions/my_action
        with:
          testing: " Amo la Programacion como nadie mas lo ha hecho. "
          dev: " Amo EL Lenguaje de Programacion Python "
          
  variables_entorno:
    name: Variables de entorno
    needs: Test_personalizado
    runs-on: ubuntu-latest

    env:
      var: Quiero ser un Desarrollador Full Stack
    
    steps:
      - name: variables
        run: echo " $var "

  
  variables_entorno_2:
    name: Metodo 2 para usar variables de entorno
    needs: variables_entorno
    runs-on: ubuntu-latest

    steps:
      - name: Variables de entorno 2
        env: 
          my_var: Sin Dormir, pero estudiando y aprendiendo lo que me gusta (Desarrollo de Software).
        run: echo " $my_var "
        


    